### ISSUE TITLE
Failed to install spi: node-gyp rebuild

### ISSUE THREAD

**Issue by nick-jonas** [RussTheAerialist/node-spi#25]
`node-gyp rebuild` is failing when I run `npm install spi` (ran with sudo as well) on a Raspberry Pi B+.  I don't know enough about node-gyp as to why this might be an issue, but do you have any ideas?

**Comment by Gamadril** [comment]
Try to update npm: `sudo npm -g install npm`. That should also update node-gyp.

**Comment by RudyJM** [comment]
Nick did you get this to work?
Also having the same issue on a Beaglebone Black. 
Tried Gamadril's solution, but it didn't work

npm ERR! spi@0.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the spi@0.2.0 install script.
npm ERR! This is most likely a problem with the spi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls spi
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.8.13-bone79
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "spi"
npm ERR! cwd /var/lib/cloud9
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE

**Comment by martrw** [comment]
Same issue here.  New install of npm.

sudo npm install spi
|

> spi@0.2.0 install /home/pi/.node-red/node_modules/spi
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.29"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/.node-red/node_modules/spi/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: unexpected eof
gyp ERR! stack     at decorate (/usr/local/lib/node_modules/npm/node_modules/fstream/lib/abstract.js:67:36)
gyp ERR! stack     at Extract.Abstract.error (/usr/local/lib/node_modules/npm/node_modules/fstream/lib/abstract.js:61:12)
gyp ERR! stack     at Extract._streamEnd (/usr/local/lib/node_modules/npm/node_modules/tar/lib/extract.js:91:35)
gyp ERR! stack     at BlockStream.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:51:8)
gyp ERR! stack     at BlockStream.emit (events.js:92:17)
gyp ERR! stack     at BlockStream._emitChunk (/usr/local/lib/node_modules/npm/node_modules/block-stream/block-stream.js:203:10)
gyp ERR! stack     at BlockStream.resume (/usr/local/lib/node_modules/npm/node_modules/block-stream/block-stream.js:58:15)
gyp ERR! stack     at Extract.Reader.resume (/usr/local/lib/node_modules/npm/node_modules/fstream/lib/reader.js:249:34)
gyp ERR! stack     at DirWriter.ondrain (stream.js:61:14)
gyp ERR! stack     at DirWriter.emit (events.js:117:20)
gyp ERR! System Linux 4.1.17+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/.node-red/node_modules/spi
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok 
npm ERR! Linux 4.1.17+
npm ERR! argv "node" "/usr/local/bin/npm" "install" "spi"
npm ERR! node v0.10.29
npm ERR! npm  v2.14.22
npm ERR! code ELIFECYCLE

npm ERR! spi@0.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the spi@0.2.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the spi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs spi
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls spi
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/.node-red/npm-debug.log

**Comment by Gamadril** [comment]
Here how I got it working on Raspbian Jessie

```
sudo apt-get update
sudo apt-get install nodejs npm nodejs-legacy
sudo npm -g install npm
npm install spi@0.1.2
```

**Comment by Kroltez** [comment]
I just did npm install node-gyp
fixed it all up for me

**Comment by ghost** [comment]
I get the same errors and non of the solutions previously mentioned work. Anyone have any light on this issue?

**Comment by riverwilliams94** [comment]
If anyone is still having this issue with Node 10, the following pull request appears to fix it: #32

**Comment by nilipta** [comment]
Still no luck in installing this module in 
`nvidia@tegra-ubuntu:~/spitest$ node -v
v10.15.0
nvidia@tegra-ubuntu:~/spitest$ npm -v
6.4.1
[spi console_log.txt](https://github.com/russtheaerialist-retired-projects/node-spi/files/2910688/spi.console_log.txt)
`
